Apply latest meta/config template
zopefoundation/zodbpickle pull request #95
Opened 2024-08-26 13:58 UTC by dataflake

2024-08-27 06:59 UTC, icemac requested changes

2024-08-27 06:59 UTC, icemac commented on src/zodbpickle/pickle_3.py
We have some per-file-ignores in setup.cfg to prevent these changes: https://github.com/zopefoundation/zodbpickle/blob/c7a9678b05b3e076a668eff7c91c398cdead25e3/setup.cfg#L14-L19

But autopep8 seems to ignore them.
We probably need some markers here, see https://pypi.org/project/autopep8/#disabling-line-by-line

2024-08-27 14:05 UTC, dataflake commented on src/zodbpickle/pickle_3.py
That marker works, please review again.

2024-08-30 06:32 UTC, icemac approved these changes

2024-08-30 06:32 UTC, merged